### PR TITLE
[SE-4304] Add single-beat for celerybeat scheduler process wrapping

### PR DESCRIPTION
**Pull request by gabor-boros**
This PR adds [`single-beat`](https://github.com/ybrs/single-beat) to the configuration to ensure celery-beat only runs on one host at a time, therefore only one scheduler schedules tasks for the workers.

In case the scheduler node or process dies, another process will take its role over within `360` (300 lock time + 60 check interval) seconds.

**Sandbox URL**: Deployed to stage

**Merge deadline**: "None" if there's no rush, "ASAP" if it's critical, or provide a specific date if there is one.

**Testing instructions**:

1. Check the steps of https://github.com/edx-olive/edx-platform/pull/66

**Author notes and concerns**:

The 360 seconds maybe too much, but it depends on the frequency of the scheduled periodic tasks. In the future, we may want to set a lower number like 60 seconds lock time and 30 seconds interval.

**Reviewers**
- [ ] @itsjeyd 
- [ ] @pkulkark

### CODE REVIEW

**Review by pkulkark — APPROVED** [review]
LGTM :+1: 

- [x] I tested this: As described in [edx-olive/edx-platform#66](https://github.com/edx-olive/edx-platform/pull/66)
- [x] I read through the code
- [ ] ~~I checked for accessibility~~ N/A
- [ ] ~~Includes documentation~~ N/A

**Comment by itsjeyd** [comment]
@gabor-boros 

> **The 360 seconds maybe too much, but it depends on the frequency of the scheduled periodic tasks.** In the future, we may want to set a lower number like 60 seconds lock time and 30 seconds interval.

Thanks for pointing this out. When you get a minute, could you reach out to the client and ask them at which frequency they will want to generate instructor reports (on stage and prod)?

**Comment by gabor-boros** [comment]
@itsjeyd I just asked Eyal about the frequency.

**Comment by itsjeyd** [comment]
@gabor-boros Great, thanks!

**Comment by itsjeyd** [comment]
> I just asked Eyal about the frequency.

For future reference, based on the results of [this conversation](https://github.com/edx-olive/configuration/pull/31#issuecomment-857671280) we will not need to make any further changes to single-beat settings in the short term.

**Pull request merged**
