### PR TITLE
[SE-3513] Fix devstack box configuration

### PR DESCRIPTION
**Pull request by gabor-boros**
This PR is about to fix based devstack image build for ginkgo.2-campus.
This change cannot be upstreamed, since it only works with the patched ginkgo branch + pymongo fix.

**Screenshots**: N/A

**Sandbox URL**: N/A

**Testing instructions**:

Testing would take a lot of time.

0. checkout this branch
1. install the required ansible dependencies (into a virtualenv)
2. cd into `vagrant/base/devstack`
3. change `configuration_version` to the this branch in `playbooks/roles/edx_ansible/vars/devstack.yml`
4. run `vagrant up`

**Author notes and concerns**:

https://app.vagrantup.com/edx-olive/boxes/ginkgo.2-campus-devstack/versions/1.0.0

**Reviewers**
- [ ] (OpenCraft internal reviewer's GitHub username goes here)

### CODE REVIEW

**Comment by clemente** [comment]
@gabor-boros 
- if I change the branch too `gabor/fix-box-creation` in the Vagrantfile mentioned at [the devstack MR](https://gitlab.com/opencraft/client/campus/campus-devstack/-/merge_requests/10) and I run `vagrant up`, I assume this playbook will be run, right?
- why are then two Vagrantfile? (one here, another at MR 10), and could we keep just one? (the one in MR 10)
- this PR wants to merge changes into `opencraft-release/ginkgo.2-campus`. The changes may be useful to fix the devstack. But this branch is also used to deploy changes to stage and production (I just checked: production uses `opencraft-release/ginkgo.2-campus`) so we'd effectively be deploying all changes in this PR to production. Some of the changes may break production since they are setting test variables or changing versions
- instead of modifying the default values in `defaults/main.yml` files here, could you leave the defaults untouched and *pass* some values through the ansible variables? I think it would be done [from this file](https://gitlab.com/opencraft/client/campus/campus-devstack/blob/gabor%2Ffix-devstack/campus-vars.yml#L1)
- Observation: the defaults are fine in this branch must be right, because production is using them (production is passing some variables, and we should do the same)
- I'd argue that the rest of the code is apparently fine too, because production is using it. I might be very wrong… But could you try reducing the changes to this branch?
  - For instance, why would we need to disable security upgrades? (mmmm… I may know why: because the background `dpkg` may crash the provisioning due to not getting the `dpkg` lock. This happened to me). But if we want to disable some things, there should be a flag (a variable) that we can pass from `campus-devstack/campus-vars.yml`
  - or why was it required to remove `Add the mongodb signing key`, or to backpin `setuptools==44.0.0`, if it appears to work well in production?
- you can take a look at which variables production is setting (e.g. [the COMMON_JWT_… ones](https://github.com/edx-olive/olive-secure/blob/aca51c620187428e96735d53a7ab62c7fbf9a893/ansible/vars/prod-olivex.yml#L86)), and then set similar ones where the devstack requires some value. But copy the approach or values into the `campus-devstack/campus-vars.yml`, not into here
- if we modify things here, we'd need to test the deployment on stage and production, and we'd need to upstream the changes too. Better not to change anything here
- there's an alternative solution: keeping a parallel configuration branch, just to build devstacks. This is also much more trouble to maintain because we'd need to keep it in sync with the other one. It would be better to use the real/official configuration branch, and pass the right variables to make it do what we want

**Comment by gabor-boros** [comment]
@clemente 

> if I change the branch too gabor/fix-box-creation in the Vagrantfile mentioned at the devstack MR and I run vagrant up, I assume this playbook will be run, right?

> why are then two Vagrantfile? (one here, another at MR 10), and could we keep just one? (the one in MR 10)

The `campus-devstack` builds on the `base devstack`. This means that both will run the playbooks defined here for devstack installation. Although it would be possible to have only one devstack, that would introduce lot of failure points. For example, in case of macOS, the MySQL client installation (python package) is a pain and the devstack build would depend on the underlying host os. Furthermore, it would eat up lot of resources and time to build a devstack VM. In case of the splitted setup (as edx did for years), the users have to download a pre-built image which could be customized, just as we do with `campus-devstack`. This was the original effort of EdX and I believe we shouldn't change on that.

> this PR wants to merge changes into opencraft-release/ginkgo.2-campus. The changes may be useful to fix the devstack. But this branch is also used to deploy changes to stage and production [...]

> instead of modifying the default values in defaults/main.yml files here, could you leave the defaults untouched and pass some values through the ansible variables? I think it would be done from this file

> you can take a look at which variables production is setting (e.g. the COMMON_JWT_… ones), and then set similar ones where the devstack requires some value. But copy the approach or values into the campus-devstack/campus-vars.yml, not into here

Yes, that's true. I did change the approach. From now on we are not rewriting the default (where it is not a must have) but use the devstack vars to configure the roles. Nice catch. 👍 

The idea of using vars was applied, but not within the campus devstack as per my above comment.

> I'd argue that the rest of the code is apparently fine too, because production is using it. I might be very wrong… But could you try reducing the changes to this branch?

Reduced 😇 

> For instance, why would we need to disable security upgrades

Those will break the devstack box creation. I did not want to burn the budget to fix something which would never reach production and already an outdated approach (I mean the vagrant based devstack here).

>  why was it required to remove Add the mongodb signing key, or to backpin setuptools==44.0.0, if it appears to work well in production?

I assume that we aren't using the latest packages within the AMIs, since the latest ubuntu Xenial image would like to install `setuptools>44` which removes the python2 compatibility completely. Furthermore, mongodb's signing key worth nothing as the referenced download server is dismantled several years ago by mongodb hence mongodb-org package cannot be installed anymore, though there is a mongodb package within the apt repos which is the exact same version we need. 🍀 

> if we modify things here, we'd need to test the deployment on stage and production, and we'd need to upstream the changes too. Better not to change anything here

As discussed in SE-3513, there is no need for upstreaming. Also, because of changing the approach, this shouldn't affect production/stage anymore.

> there's an alternative solution: keeping a parallel configuration branch, just to build devstacks. This is also much more trouble to maintain because we'd need to keep it in sync with the other one. It would be better to use the real/official configuration branch, and pass the right variables to make it do what we want

As we discussed in SE-3513 that could be done and may would be a good enough idea to have a separate configuration branch only for [campus-]devstack. As we are passing the modifications as variables, we could even merge if we want. In case you feel it is safer to have a separate branch, we can have it and I'll adjust the related MR10.

**Comment by clemente** [comment]
@gabor-boros I think the new approach makes it more organized, and it separates the „just a variable“ changes (now inside devstack.yml) from the „code needs to be changed“ changes (the rest).


Right now we can't merge, because it would remove some mongo steps (Add the mongodb signing key, Add the mongodb repo to the sources list). As you said, they may not be used, but we'd have to check in stage/production and make sure nothing breaks, and this task already grew too large. So for now we don't need to merge (as decided in SE-3513), so please change MR-10 to mention the new branch.

Then we will cover our concerns, about minimizing the amount of changes, and documenting the custom branch.

> since the latest ubuntu Xenial image would like to install setuptools>44 which removes the python2 compatibility completely.
@gabor-boros Optional change: in your comment `We MUST backpin setuptools anyways`, could you mention this reason? (python2 compatibility).

:+1:

- [X] I tested this: I built a new devstack! Through [MR 10](https://gitlab.com/opencraft/client/campus/campus-devstack/-/merge_requests/10) by specifying this branch, and it worked (LMS/CMS, with the theme, and I could log in to Studio and create a course). I didn't test all features inside the devstack; they can be fixed later.
- [X] I read through the code, makes sense and now it's smaller
  - The `edx_platform_version: 'pooja/cherry-pick-pymongo-upgrade'` is the current one
   - at https://github.com/edx-olive/cs_comments_service/commits/opencraft-release/ginkgo.2-campus, the 2 commits specify the ruby version (ruby 1.9.3p551) and the codecov-ruby version. The rest of the packages that appear on the diff aren't affect (the 2nd commit reverts the 1st one).
- [X] I checked for accessibility issues
- [X] Includes documentation: there will be in MR 10. And in comments
- the [new box](https://app.vagrantup.com/edx-olive/boxes/ginkgo.2-campus-devstack/versions/1.0.0) is uploaded

@gabor-boros Approved, but please *don't merge* it into the official branch; instead leave it as a new branch.

**Comment by gabor-boros** [comment]
Updated the documentation of MR10. Closing this PR now it is approved, to ensure nobody will merge accidentally.

**Pull request closed without merging**
